import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import App from './App'
import { api } from './lib/api'
import { createOrderSocket } from './lib/socket'

vi.mock('./lib/api', () => ({ api: { getMenu: vi.fn(), createOrder: vi.fn(), getOrder: vi.fn() } }))
vi.mock('./lib/socket', () => ({ createOrderSocket: vi.fn() }))
const mockedApi = vi.mocked(api)
const mockedSocket = vi.mocked(createOrderSocket)
const dish = { _id: '65fbf2f0df5a0029aab00001', name: 'Seasonal Risotto', description: 'Mushrooms and parmesan', price: 12.5, category: 'Main Course', image: 'risotto.jpg', available: true }
const renderApp = () => render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><App /></QueryClientProvider>)
const socket = () => ({ connected: false, on: vi.fn(), off: vi.fn(), emit: vi.fn(), disconnect: vi.fn() })

afterEach(() => { vi.resetAllMocks(); localStorage.clear() })

describe('ordering flow', () => {
  it('shows menu loading and empty states from the API query', async () => {
    let resolveMenu: (value: typeof dish[]) => void = () => undefined
    mockedApi.getMenu.mockReturnValue(new Promise((resolve) => { resolveMenu = resolve }) as never)
    renderApp()
    expect(screen.getByRole('status')).toHaveTextContent('Loading today’s menu')
    resolveMenu([])
    expect(await screen.findByText('The kitchen is updating today’s menu.')).toBeInTheDocument()
  })

  it('renders fetched menu data, manages cart quantities, and removes an item', async () => {
    mockedApi.getMenu.mockResolvedValue([dish])
    const user = userEvent.setup()
    renderApp()
    expect(await screen.findByText('Seasonal Risotto')).toBeInTheDocument()
    expect(screen.getByText('Main Course')).toBeInTheDocument()
    expect(screen.getByAltText('Seasonal Risotto')).toHaveAttribute('src', 'risotto.jpg')
    await user.click(screen.getByRole('button', { name: /add seasonal risotto/i }))
    expect(screen.getByRole('button', { name: 'Increase Seasonal Risotto from menu' })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Open cart' }))
    expect(screen.getByText('Total').parentElement).toHaveTextContent('Total$12.50')
    expect(screen.getByRole('heading', { name: /your cart \(1\)/i })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Increase Seasonal Risotto from menu' }))
    expect(screen.getByRole('heading', { name: /your cart \(2\)/i })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Decrease Seasonal Risotto from menu' }))
    await user.click(screen.getByRole('button', { name: /remove seasonal risotto/i }))
    expect(screen.getByText(/cart is empty/i)).toBeInTheDocument()
  })

  it('shows a menu fetch error and never renders hard-coded dishes', async () => {
    mockedApi.getMenu.mockRejectedValue(new Error('offline'))
    renderApp()
    expect(await screen.findByRole('alert')).toHaveTextContent('couldn’t load the menu')
    expect(screen.queryByText('Truffle Mushroom Risotto')).not.toBeInTheDocument()
  })

  it('validates checkout, submits server payload, and tracks the persisted order', async () => {
    mockedSocket.mockReturnValue(socket() as never)
    mockedApi.getMenu.mockResolvedValue([dish])
    mockedApi.createOrder.mockResolvedValue({ _id: '65fbf2f0df5a0029aab00099', trackingToken: 'token', status: 'RECEIVED', totalAmount: 12.5, customer: { name: 'Ada Lovelace', phone: '+1 555 123 4567', address: '12 Analytical Engine Way' }, items: [{ menuItemId: dish._id, name: dish.name, price: 12.5, quantity: 1 }] })
    mockedApi.getOrder.mockResolvedValue({ _id: '65fbf2f0df5a0029aab00099', status: 'PREPARING', totalAmount: 12.5, customer: { name: 'Ada Lovelace', phone: '+1 555 123 4567', address: '12 Analytical Engine Way' }, items: [] })
    const user = userEvent.setup()
    renderApp()
    await screen.findByText(dish.name)
    await user.click(screen.getByRole('button', { name: /add seasonal risotto/i }))
    await user.click(screen.getByRole('button', { name: 'Open cart' }))
    await user.click(screen.getByRole('button', { name: /^checkout/i }))
    expect(screen.getByRole('button', { name: 'Place order · $12.50' })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /place order/i }))
    expect(await screen.findByText('Enter your name')).toBeInTheDocument()
    await user.type(screen.getByPlaceholderText('Your full name'), 'Ada Lovelace')
    await user.type(screen.getByPlaceholderText('(555) 123-4567'), '+1 555 123 4567')
    await user.type(screen.getByPlaceholderText(/street address/i), '12 Analytical Engine Way')
    await user.click(screen.getByRole('button', { name: /place order/i }))
    await waitFor(() => expect(mockedApi.createOrder.mock.calls[0]?.[0]).toEqual({ customer: { name: 'Ada Lovelace', phone: '+1 555 123 4567', address: '12 Analytical Engine Way' }, items: [{ menuItemId: dish._id, quantity: 1 }] }))
    expect(await screen.findByText('preparing')).toBeInTheDocument()
    expect(mockedApi.getOrder).toHaveBeenCalledWith('65fbf2f0df5a0029aab00099', 'token')
  })

  it('shows submission state while checkout is pending', async () => {
    mockedApi.getMenu.mockResolvedValue([dish])
    mockedApi.createOrder.mockReturnValue(new Promise(() => undefined) as never)
    const user = userEvent.setup()
    renderApp()
    await screen.findByText(dish.name)
    await user.click(screen.getByRole('button', { name: /add seasonal/i }))
    await user.click(screen.getByRole('button', { name: 'Open cart' }))
    await user.click(screen.getByRole('button', { name: /^checkout/i }))
    await user.type(screen.getByPlaceholderText('Your full name'), 'Ada Lovelace')
    await user.type(screen.getByPlaceholderText('(555) 123-4567'), '+1 555 123 4567')
    await user.type(screen.getByPlaceholderText(/street address/i), '12 Analytical Engine Way')
    await user.click(screen.getByRole('button', { name: /place order/i }))
    expect(await screen.findByRole('button', { name: 'Placing order…' })).toBeDisabled()
  })

  it('reuses one idempotency key for rapid submits and creates a new key after success', async () => {
    mockedSocket.mockReturnValue(socket() as never)
    mockedApi.getMenu.mockResolvedValue([dish])
    mockedApi.createOrder.mockResolvedValue({ _id: '65fbf2f0df5a0029aab00099', trackingToken: 'token', status: 'RECEIVED', totalAmount: 12.5, customer: { name: 'Ada', phone: '+1 555 123 4567', address: '12 Analytical Engine Way' }, items: [] })
    const user = userEvent.setup()
    renderApp()
    await screen.findByText(dish.name)
    await user.click(screen.getByRole('button', { name: /add seasonal/i }))
    await user.click(screen.getByRole('button', { name: 'Open cart' }))
    await user.click(screen.getByRole('button', { name: /^checkout/i }))
    await user.type(screen.getByPlaceholderText('Your full name'), 'Ada')
    await user.type(screen.getByPlaceholderText('(555) 123-4567'), '+1 555 123 4567')
    await user.type(screen.getByPlaceholderText(/street address/i), '12 Analytical Engine Way')
    const form = screen.getByRole('button', { name: /place order/i }).closest('form')!
    fireEvent.submit(form)
    fireEvent.submit(form)
    await waitFor(() => expect(mockedApi.createOrder).toHaveBeenCalledTimes(2))
    expect(mockedApi.createOrder.mock.calls[0][1]).toBe(mockedApi.createOrder.mock.calls[1][1])
  })

  it('shows an order tracking error when the persisted order cannot be retrieved', async () => {
    mockedSocket.mockReturnValue(socket() as never)
    mockedApi.getMenu.mockResolvedValue([dish])
    mockedApi.createOrder.mockResolvedValue({ _id: '65fbf2f0df5a0029aab00099', trackingToken: 'token', status: 'RECEIVED', totalAmount: 12.5, customer: { name: 'Ada', phone: '+1 555 123 4567', address: '12 Analytical Engine Way' }, items: [] })
    mockedApi.getOrder.mockRejectedValue({ response: { status: 404 } })
    const user = userEvent.setup()
    renderApp()
    await screen.findByText(dish.name)
    await user.click(screen.getByRole('button', { name: /add seasonal/i }))
    await user.click(screen.getByRole('button', { name: 'Open cart' }))
    await user.click(screen.getByRole('button', { name: /^checkout/i }))
    await user.type(screen.getByPlaceholderText('Your full name'), 'Ada')
    await user.type(screen.getByPlaceholderText('(555) 123-4567'), '+1 555 123 4567')
    await user.type(screen.getByPlaceholderText(/street address/i), '12 Analytical Engine Way')
    await user.click(screen.getByRole('button', { name: /place order/i }))
    expect(await screen.findByRole('alert')).toHaveTextContent('couldn’t retrieve this order’s status')
  })

  it('handles checkout API failures without pretending an order exists', async () => {
    mockedApi.getMenu.mockResolvedValue([dish])
    mockedApi.createOrder.mockRejectedValue({ response: { data: { error: { message: 'Menu item is unavailable' } } } })
    const user = userEvent.setup()
    renderApp()
    await screen.findByText(dish.name)
    await user.click(screen.getByRole('button', { name: /add seasonal risotto/i }))
    await user.click(screen.getByRole('button', { name: 'Open cart' }))
    await user.click(screen.getByRole('button', { name: /^checkout/i }))
    await user.type(screen.getByPlaceholderText('Your full name'), 'Ada Lovelace')
    await user.type(screen.getByPlaceholderText('(555) 123-4567'), '+1 555 123 4567')
    await user.type(screen.getByPlaceholderText(/street address/i), '12 Analytical Engine Way')
    await user.click(screen.getByRole('button', { name: /place order/i }))
    expect(await screen.findByText('Menu item is unavailable')).toBeInTheDocument()
    expect(screen.queryByText('We’re on it.')).not.toBeInTheDocument()
  })

  it('subscribes once and updates visible status only for a valid matching realtime event', async () => {
    const fakeSocket = socket()
    mockedSocket.mockReturnValue(fakeSocket as never)
    mockedApi.getMenu.mockResolvedValue([dish])
    mockedApi.createOrder.mockResolvedValue({ _id: '65fbf2f0df5a0029aab00099', trackingToken: 'token', status: 'RECEIVED', totalAmount: 12.5, customer: { name: 'Ada', phone: '+1 555 123 4567', address: '12 Analytical Engine Way' }, items: [] })
    mockedApi.getOrder.mockResolvedValue({ _id: '65fbf2f0df5a0029aab00099', status: 'RECEIVED', totalAmount: 12.5, customer: { name: 'Ada', phone: '+1 555 123 4567', address: '12 Analytical Engine Way' }, items: [] })
    const user = userEvent.setup()
    const view = renderApp()
    await screen.findByText(dish.name)
    await user.click(screen.getByRole('button', { name: /add seasonal/i }))
    await user.click(screen.getByRole('button', { name: 'Open cart' }))
    await user.click(screen.getByRole('button', { name: /^checkout/i }))
    await user.type(screen.getByPlaceholderText('Your full name'), 'Ada')
    await user.type(screen.getByPlaceholderText('(555) 123-4567'), '+1 555 123 4567')
    await user.type(screen.getByPlaceholderText(/street address/i), '12 Analytical Engine Way')
    await user.click(screen.getByRole('button', { name: /place order/i }))
    await screen.findByText('received')
    const handler = fakeSocket.on.mock.calls.find(([event]) => event === 'order:status-updated')?.[1] as (payload: unknown) => void
    const onConnect = fakeSocket.on.mock.calls.find(([event]) => event === 'connect')?.[1] as () => void
    onConnect()
    expect(fakeSocket.emit).toHaveBeenCalledWith('order:subscribe', { orderId: '65fbf2f0df5a0029aab00099', trackingToken: 'token' })
    expect(fakeSocket.on).toHaveBeenCalledWith('order:status-updated', expect.any(Function))
    handler({ orderId: 'other-order', status: 'PREPARING', updatedAt: new Date().toISOString() })
    expect(screen.getByText('received')).toBeInTheDocument()
    handler({ orderId: '65fbf2f0df5a0029aab00099', status: 'PREPARING', updatedAt: new Date().toISOString() })
    expect(await screen.findByText('preparing')).toBeInTheDocument()
    handler({ orderId: '65fbf2f0df5a0029aab00099', status: 'NOT_A_STATUS', updatedAt: new Date().toISOString() })
    expect(screen.getByText('preparing')).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Close order tracking' }))
    expect(fakeSocket.off).toHaveBeenCalledWith('order:status-updated', expect.any(Function))
    expect(fakeSocket.disconnect).toHaveBeenCalledOnce()
    view.unmount()
  })

  it('preserves multiple tracked orders, lets the customer select either one, and scopes status updates by ID', async () => {
    const first = { _id: '65fbf2f0df5a0029aaa001', status: 'RECEIVED' as const, totalAmount: 12.5, customer: { name: 'Ada', phone: '+1 555 123 4567', address: 'First Street' }, items: [{ menuItemId: dish._id, name: dish.name, price: 12.5, quantity: 1 }] }
    const second = { _id: '65fbf2f0df5a0029bbb002', status: 'PREPARING' as const, totalAmount: 25, customer: { name: 'Grace', phone: '+1 555 111 2222', address: 'Second Street' }, items: [{ menuItemId: dish._id, name: dish.name, price: 12.5, quantity: 2 }] }
    localStorage.setItem('trackedOrders', JSON.stringify([{ id: first._id, trackingToken: 'first-token' }, { id: second._id, trackingToken: 'second-token' }]))
    const fakeSocket = socket()
    mockedSocket.mockReturnValue(fakeSocket as never)
    mockedApi.getMenu.mockResolvedValue([dish])
    mockedApi.getOrder.mockImplementation(async (id) => id === first._id ? first : second)
    const user = userEvent.setup()
    renderApp()
    await user.click(screen.getByRole('button', { name: 'Track order' }))
    const firstCard = await screen.findByText('Order #aaa001').then((element) => element.closest('article')!)
    const secondCard = screen.getByText('Order #bbb002').closest('article')!
    expect(within(firstCard).getByText('RECEIVED')).toBeInTheDocument()
    expect(within(secondCard).getByText('PREPARING')).toBeInTheDocument()
    const handler = fakeSocket.on.mock.calls.find(([event]) => event === 'order:status-updated')?.[1] as (payload: unknown) => void
    handler({ orderId: first._id, status: 'PREPARING', updatedAt: new Date().toISOString() })
    expect(await within(firstCard).findByText('PREPARING')).toBeInTheDocument()
    expect(within(secondCard).getByText('PREPARING')).toBeInTheDocument()
    await user.click(within(firstCard).getByRole('button', { name: 'Track order' }))
    expect(await screen.findByText(/First Street/)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Close order tracking' }))
    await user.click(screen.getByRole('button', { name: 'Track order' }))
    await user.click(within(screen.getByText('Order #bbb002').closest('article')!).getByRole('button', { name: 'Track order' }))
    expect(await screen.findByText(/Second Street/)).toBeInTheDocument()
  })
})
